apiVersion: v2
name: observability-operator
description: The observability-operator manages the Giant Swarm observability platform.
home: https://github.com/giantswarm/observability-operator
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
version: 0.59.0
appVersion: 0.59.0
annotations:
  io.giantswarm.application.team: "atlas"
  config.giantswarm.io/version: 1.x.x
